services:
  db:
    image: postgres:15-alpine
    container_name: biscoli-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biscoli
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Este mapeo asegura que schema.sql se ejecute automáticamente la primera vez que se crea la base de datos
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: biscoli-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@biscoli.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

#   api:
#     build: .
#     container_name: biscoli_api
#     environment:
#       # Depend on db service and use its container name as host
#       DATABASE_URL: postgres://postgres:postgres@db:5432/biscoli
#       WOMPI_ENVIRONMENT: sandbox
#       # Reemplaza estas llaves con tus valores de Wompi reales cuando corras el contenedor
#       WOMPI_PRIVATE_KEY: ${WOMPI_PRIVATE_KEY:-}
#       WOMPI_PUBLIC_KEY: ${WOMPI_PUBLIC_KEY:-}
#       WOMPI_INTEGRITY_SECRET: ${WOMPI_INTEGRITY_SECRET:-}
#       WOMPI_EVENTS_SECRET: ${WOMPI_EVENTS_SECRET:-}
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#     restart: unless-stopped

volumes:
  postgres_data:
